import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Header from './components/Header'



export const metadata = {
  title: 'Ivana Sosa Cordero | Front end developer',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={GeistSans.className}>
      
      <body >
      <Header />

        {children}
        </body>
    </html>
  )
}
